# Generated by Django 5.0 on 2025-06-05 16:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magistrates', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='magistrate',
            options={'verbose_name': 'Magistrat', 'verbose_name_plural': 'Magistrats'},
        ),
        migrations.RemoveField(
            model_name='magistrate',
            name='name',
        ),
        migrations.AddField(
            model_name='magistrate',
            name='court_name',
            field=models.CharField(default='Tribunal de Grande Instance', max_length=200, verbose_name='Nom du tribunal'),
        ),
        migrations.AddField(
            model_name='magistrate',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création'),
        ),
        migrations.AddField(
            model_name='magistrate',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='magistrate',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Prénom'),
        ),
        migrations.AddField(
            model_name='magistrate',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nom'),
        ),
        migrations.AddField(
            model_name='magistrate',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone'),
        ),
        migrations.AddField(
            model_name='magistrate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour'),
        ),
    ]
