"""
Django settings for prison_management project.

Generated by 'django-admin startproject' using Django 5.0.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os
from pathlib import Path
from django.contrib.messages import constants as messages
from apps import authentication

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-dk&17)h*f&!_%6@s52f6vw549d7$ld7gnj4yqw0*b5&3!s)pk-'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []
CSRF_COOKIE_SECURE = False  # Mettez True en


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',


    # Applications tierces
    'crispy_forms' ,
    'crispy_bootstrap5' ,
    'allauth' ,
    'django_celery_beat',
    'chartjs',
    'axes',  # Pour la sécurité
    'allauth.account' ,
    'allauth.socialaccount' ,
    'notifications' ,

    # Applications locales
    'apps.inmates' ,
    'apps.prisons.apps.PrisonsConfig',
    'apps.authentication.apps.AuthenticationConfig',  # Utilisez ce format
    'apps.notifications.apps.NotificationConfig' ,  # Assurez-vous que le nom correspond exactement
    'apps.magistrates',
    'apps.guards' ,


]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware', # ici assistance IA sur
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'axes.middleware.AxesMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',  # Ajoutez cette ligne

]

ROOT_URLCONF = 'prison_management.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                #'prison_management.context_processors.nav_context',
            ],
        },
    },
]
# Messages configuration
MESSAGE_TAGS = {
    messages.DEBUG: 'alert-info',
    messages.INFO: 'alert-info',
    messages.SUCCESS: 'alert-success',
    messages.WARNING: 'alert-warning',
    messages.ERROR: 'alert-danger',
}
# Configuration Jazzmin

JAZZMIN_SETTINGS = {
    "site_title": "Système Pénitentiaire" ,
    "custom_js": "js/charts.js",
    "site_header": "Administration Prison" ,
    "site_brand": "Prison Admin" ,
    "site_logo": "chemin/vers/votre/logo.png" ,
    "welcome_sign": "Bienvenue dans l'administration du système pénitentiaire" ,
    "copyright": "Prison Management System" ,
    "search_model": ["guards.User" , "guards.IncidentReport"] ,

    "topmenu_links": [
        {"name": "Accueil" , "url": "admin:index"} ,
        {"name": "Site" , "url": "admin:index"} ,
        {"model": "guards.User"} ,
    ] ,

    "show_sidebar": True ,
    "navigation_expanded": True ,

    "icons": {
        "guards.User": "fas fa-user-shield" ,
        "guards.IncidentReport": "fas fa-exclamation-triangle" ,
        "guards.TeamUnit": "fas fa-users" ,
        "guards.Schedule": "fas fa-calendar-alt" ,
    } ,

    "default_icon_parents": "fas fa-chevron-circle-right" ,
    "default_icon_children": "fas fa-circle" ,

    "related_modal_active": True ,
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False ,
    "footer_small_text": False ,
    "body_small_text": False ,
    "brand_small_text": False ,
    "brand_colour": "navbar-primary" ,
    "accent": "accent-primary" ,
    "navbar": "navbar-dark" ,
    "no_navbar_border": False ,
    "navbar_fixed": False ,
    "layout_boxed": False ,
    "footer_fixed": False ,
    "sidebar_fixed": True ,
    "sidebar": "sidebar-dark-primary" ,
    "sidebar_nav_small_text": False ,
    "sidebar_disable_expand": False ,
    "sidebar_nav_child_indent": True ,
    "sidebar_nav_compact_style": False ,
    "sidebar_nav_legacy_style": False ,
    "sidebar_nav_flat_style": False ,
    "theme": "default" ,
    "dark_mode_theme": None ,
    "button_classes": {
        "primary": "btn-primary" ,
        "secondary": "btn-secondary" ,
        "info": "btn-info" ,
        "warning": "btn-warning" ,
        "danger": "btn-danger" ,
        "success": "btn-success"
    }
}

# Configuration du stockage des messages
MESSAGE_STORAGE = 'django.contrib.messages.storage.session.SessionStorage'


WSGI_APPLICATION = 'prison_management.wsgi.application'

# Configuration de Crispy Forms
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

AUTH_USER_MODEL = 'authentication.User'
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'login'
LOGIN_URL = 'login'

# Configuration de l'authentification à deux facteurs
#TWO_FACTOR_FORCE_OTP_ADMIN = True
#TWO_FACTOR_PATCH_ADMIN = True


# Configuration des permissions
AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesBackend',
    'django.contrib.auth.backends.ModelBackend',
]
# Configuration de la sécurité
AXES_FAILURE_LIMIT = 5  # Nombre de tentatives avant verrouillage
AXES_LOCK_OUT_AT_FAILURE = True  # Verrouiller après échec
AXES_USE_USER_AGENT = True  # Utiliser l'agent utilisateur
AXES_RESET_ON_SUCCESS = True  # Réinitialiser le compteur après connexion réussie
AXES_LOCKOUT_PARAMETERS = ['ip_address', 'username']


# Configuration Celery pour les tâches périodiques
CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'

# Configuration des notifications
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [('127.0.0.1', 6379)],
        },
    },
}


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

# Configuration de la langue
LANGUAGE_CODE = 'fr-fr'
TIME_ZONE = 'Africa/Libreville'


USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / "static",
    BASE_DIR / "node_modules/@fortawesome/fontawesome-free",
]

# Configuration des fichiers média
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Configuration email pour le développement
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
# Pour la production, utilisez plutôt :
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.votreserveur.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'votre@email.com'
# EMAIL_HOST_PASSWORD = 'votremotdepasse'
