# Generated by Django 5.0 on 2025-06-05 15:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('magistrates', '0001_initial'),
        ('prisons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inmate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('photo', models.ImageField(upload_to='inmates_photos/')),
                ('admission_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('release_date', models.DateTimeField(blank=True, null=True)),
                ('health_status', models.TextField()),
                ('is_recidivist', models.BooleanField(default=False)),
                ('crime_description', models.TextField()),
                ('current_prison', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prisons.prison')),
            ],
            options={
                'ordering': ['-admission_date'],
            },
        ),
        migrations.CreateModel(
            name='Detention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warrant_pdf', models.FileField(upload_to='detention_warrants/')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('magistrate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='magistrates.magistrate')),
                ('inmate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inmates.inmate')),
            ],
        ),
    ]
