# Generated by Django 5.0 on 2025-06-05 17:06

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmates', '0003_alter_inmate_options_alter_inmate_admission_date_and_more'),
        ('magistrates', '0002_alter_magistrate_options_remove_magistrate_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warrant_pdf', models.FileField(help_text='Format accepté : PDF', upload_to='detention_warrants/', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Mandat de détention')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de début')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Date de fin')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('inmate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inmates.inmate', verbose_name='Détenu')),
                ('magistrate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='magistrates.magistrate', verbose_name='Magistrat')),
            ],
            options={
                'verbose_name': 'Détention',
                'verbose_name_plural': 'Détentions',
                'ordering': ['-start_date'],
            },
        ),
    ]
