# Generated by Django 4.2.22 on 2025-06-06 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inmates', '0004_detention'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_name', models.CharField(max_length=100)),
                ('visitor_relation', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('approved', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('inmate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='inmates.inmate')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
