# Generated by Django 5.0 on 2025-06-05 20:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guards', '0001_initial'),
        ('inmates', '0004_detention'),
        ('prisons', '0002_alter_prison_options_prison_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuardCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('issuing_authority', models.CharField(max_length=200, verbose_name='Autorité émettrice')),
                ('validity_period', models.IntegerField(verbose_name='Période de validité (mois)')),
            ],
            options={
                'verbose_name': 'Certification',
                'verbose_name_plural': 'Certifications',
            },
        ),
        migrations.CreateModel(
            name='GuardSpecialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('description', models.TextField(verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Spécialisation',
                'verbose_name_plural': 'Spécialisations',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, verbose_name='Adresse'),
        ),
        migrations.AddField(
            model_name='user',
            name='current_shift',
            field=models.CharField(blank=True, choices=[('MORNING', 'Matin (6h-14h)'), ('AFTERNOON', 'Après-midi (14h-22h)'), ('NIGHT', 'Nuit (22h-6h)')], max_length=20, null=True, verbose_name='Service actuel'),
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date de naissance'),
        ),
        migrations.AddField(
            model_name='user',
            name='hire_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name="Date d'embauche"),
        ),
        migrations.AddField(
            model_name='user',
            name='is_on_duty',
            field=models.BooleanField(default=False, verbose_name='En service'),
        ),
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='guards_photos/%Y/%m/', verbose_name='Photo'),
        ),
        migrations.AddField(
            model_name='user',
            name='rank',
            field=models.CharField(choices=[('TRAINEE', 'Stagiaire'), ('GUARD', 'Gardien'), ('SENIOR', 'Gardien Principal'), ('CHIEF', 'Chef de Service'), ('SUPERVISOR', 'Superviseur')], default='GUARD', max_length=20, verbose_name='Grade'),
        ),
        migrations.AddField(
            model_name='user',
            name='certifications',
            field=models.ManyToManyField(blank=True, related_name='certified_guards', to='guards.guardcertification', verbose_name='Certifications'),
        ),
        migrations.CreateModel(
            name='GuardShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Début du service')),
                ('end_time', models.DateTimeField(verbose_name='Fin du service')),
                ('area', models.CharField(max_length=100, verbose_name='Zone assignée')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Service terminé')),
                ('guard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='guards.user', verbose_name='Garde')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['-start_time'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='specializations',
            field=models.ManyToManyField(blank=True, related_name='specialized_guards', to='guards.guardspecialization', verbose_name='Spécialisations'),
        ),
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('incident_date', models.DateTimeField(verbose_name="Date et heure de l'incident")),
                ('location', models.CharField(max_length=100, verbose_name='Lieu')),
                ('severity', models.CharField(choices=[('LOW', 'Faible'), ('MEDIUM', 'Moyen'), ('HIGH', 'Élevé'), ('CRITICAL', 'Critique')], max_length=10, verbose_name='Gravité')),
                ('description', models.TextField(verbose_name='Description')),
                ('immediate_action', models.TextField(verbose_name='Actions immédiates prises')),
                ('follow_up_action', models.TextField(blank=True, verbose_name='Actions de suivi')),
                ('status', models.CharField(choices=[('OPEN', 'Ouvert'), ('INVESTIGATING', "En cours d'investigation"), ('RESOLVED', 'Résolu'), ('CLOSED', 'Fermé')], default='OPEN', max_length=20, verbose_name='Statut')),
                ('attachments', models.FileField(blank=True, null=True, upload_to='incident_reports/%Y/%m/', verbose_name='Pièces jointes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_incidents', to='guards.user', verbose_name='Fermé par')),
                ('involved_guards', models.ManyToManyField(blank=True, related_name='involved_incidents', to='guards.user', verbose_name='Gardes impliqués')),
                ('involved_inmates', models.ManyToManyField(blank=True, related_name='involved_incidents', to='inmates.inmate', verbose_name='Détenus impliqués')),
                ('reporting_guard', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reported_incidents', to='guards.user', verbose_name='Garde rapporteur')),
                ('witnesses', models.ManyToManyField(blank=True, related_name='witnessed_incidents', to='guards.user', verbose_name='Témoins')),
            ],
            options={
                'verbose_name': "Rapport d'incident",
                'verbose_name_plural': "Rapports d'incidents",
                'ordering': ['-incident_date'],
            },
        ),
        migrations.CreateModel(
            name='TeamUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="Nom de l'équipe")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Équipe active')),
                ('leader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_teams', to='guards.user', verbose_name="Chef d'équipe")),
                ('members', models.ManyToManyField(related_name='team_memberships', to='guards.user', verbose_name='Membres')),
                ('prison', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teams', to='prisons.prison', verbose_name='Prison')),
            ],
            options={
                'verbose_name': 'Unité',
                'verbose_name_plural': 'Unités',
                'unique_together': {('name', 'prison')},
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(verbose_name='Date de fin')),
                ('rotation_pattern', models.CharField(choices=[('2X2', '2 jours travail / 2 jours repos'), ('3X2', '3 jours travail / 2 jours repos'), ('4X4', '4 jours travail / 4 jours repos'), ('5X2', '5 jours travail / 2 jours repos'), ('7X7', '7 jours travail / 7 jours repos')], max_length=50, verbose_name='Pattern de rotation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('is_active', models.BooleanField(default=True, verbose_name='Planning actif')),
                ('guard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='guards.user', verbose_name='Garde')),
                ('shifts', models.ManyToManyField(blank=True, related_name='schedule_shifts', to='guards.guardshift', verbose_name='Services planifiés')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_schedules', to='guards.teamunit', verbose_name='Unité')),
            ],
            options={
                'verbose_name': 'Planning',
                'verbose_name_plural': 'Plannings',
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='current_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_members', to='guards.teamunit', verbose_name='Équipe actuelle'),
        ),
    ]
