# Generated by Django 5.0 on 2025-06-05 23:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guards', '0002_guardcertification_guardspecialization_user_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentreport',
            name='reporter',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_reported_incidents', to=settings.AUTH_USER_MODEL, verbose_name='Rapporteur'),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='reporting_guard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guard_reported_incidents', to='guards.user', verbose_name='Garde rapporteur'),
        ),
    ]
