# Generated by Django 5.0 on 2025-06-05 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('province', models.CharField(choices=[('EST', 'Estuaire'), ('HO', 'Haut-Ogooué'), ('MO', 'Moyen-Ogooué'), ('NGO', 'Ngounié'), ('NY', 'Nyanga'), ('OI', 'Ogooué-Ivindo'), ('OL', 'Ogooué-Lolo'), ('OM', 'Ogooué-Maritime'), ('WN', 'Woleu-Ntem')], max_length=3)),
                ('capacity', models.IntegerField()),
                ('current_population', models.IntegerField(default=0)),
            ],
        ),
    ]
