# Generated by Django 5.0 on 2025-06-05 16:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prisons', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prison',
            options={'verbose_name': 'Prison', 'verbose_name_plural': 'Prisons'},
        ),
        migrations.AddField(
            model_name='prison',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création'),
        ),
        migrations.AddField(
            model_name='prison',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour'),
        ),
        migrations.AlterField(
            model_name='prison',
            name='capacity',
            field=models.IntegerField(verbose_name='Capacité'),
        ),
        migrations.AlterField(
            model_name='prison',
            name='current_population',
            field=models.IntegerField(default=0, verbose_name='Population actuelle'),
        ),
        migrations.AlterField(
            model_name='prison',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nom de la prison'),
        ),
        migrations.AlterField(
            model_name='prison',
            name='province',
            field=models.CharField(choices=[('EST', 'Estuaire'), ('HO', 'Haut-Ogooué'), ('MO', 'Moyen-Ogooué'), ('NGO', 'Ngounié'), ('NY', 'Nyanga'), ('OI', 'Ogooué-Ivindo'), ('OL', 'Ogooué-Lolo'), ('OM', 'Ogooué-Maritime'), ('WN', 'Woleu-Ntem')], max_length=3, verbose_name='Province'),
        ),
    ]
